version: "3.9"

services:
  postgressql:
    image: postgres:16.4-alpine3.20
    ports:
      - 54321:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=webtest01_go_db
    volumes:
      - webtest_data-db:/var/lib/postgresql/data

volumes:
  webtest_data-db: