# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Web Test01 Audit
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set Up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Verify Dependencies
      run: go mod verify

    - name: Build 
      run: go build -v ./...

    - name: Run Go Vet
      run: go vet ./...

    - name: Install Staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run Staticcheck
      run: staticcheck ./...

    - name: Run Tests
      run: go test -v ./tests/...
